services:
  app:
    build: .
    container_name: amelia-sage-admin
    restart: always
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: amelia-sage-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
