import type { IMindfulExerciseService } from "@/Services/interfaces";
import type { ExerciseCategory, ExerciseSubCategory } from "@/types";

// Mock Data
const MOCK_CATEGORIES: ExerciseCategory[] = [
  {
    id: "yoga",
    name: "Yoga Exercises",
    subCategories: [
      {
        id: "floor-yoga",
        name: "Floor Yoga",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "fy-1",
            title: "Child's Pose Asana",
            subtitle: "Releases lower-back tension and gently calms the nervous system.",
            duration: "5 mins",
            description: "Releases lower-back tension and gently calms the nervous system.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "fy-2",
            title: "Cat-Cow Stretch",
            subtitle: "Improves spinal flexibility and relieves tension in the back and neck.",
            duration: "6 mins",
            description: "Improves spinal flexibility and relieves tension in the back and neck.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "fy-3",
            title: "Supine Twist",
            subtitle: "A restorative twist that releases the spine and massages abdominal organs.",
            duration: "8 mins",
            description:
              "A restorative twist that releases the spine and massages abdominal organs.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "fy-4",
            title: "Legs Up the Wall",
            subtitle: "Reduces fatigue and anxiety by gently reversing blood flow.",
            duration: "10 mins",
            description: "Reduces fatigue and anxiety by gently reversing blood flow.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "seated-yoga",
        name: "Seated Yoga",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "sy-1",
            title: "Seated Forward Bend",
            subtitle: "Stretches the hamstrings and lower back while calming the mind.",
            duration: "5 mins",
            description: "Stretches the hamstrings and lower back while calming the mind.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "sy-2",
            title: "Seated Spinal Twist",
            subtitle: "Improves digestion and relieves tension in the spine.",
            duration: "6 mins",
            description: "Improves digestion and relieves tension in the spine.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "sy-3",
            title: "Bound Angle Pose",
            subtitle: "Opens the hips and groin while promoting relaxation.",
            duration: "7 mins",
            description: "Opens the hips and groin while promoting relaxation.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "sy-4",
            title: "Staff Pose",
            subtitle: "Strengthens the back and improves posture and focus.",
            duration: "4 mins",
            description: "Strengthens the back and improves posture and focus.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "power-yoga",
        name: "Power Yoga",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "py-1",
            title: "Sun Salutation A",
            subtitle: "A dynamic flowing sequence that builds heat and energises the body.",
            duration: "10 mins",
            description: "A dynamic flowing sequence that builds heat and energises the body.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "py-2",
            title: "Warrior II Flow",
            subtitle: "Builds leg strength and endurance while opening the hips.",
            duration: "12 mins",
            description: "Builds leg strength and endurance while opening the hips.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "py-3",
            title: "Chaturanga Push-Up",
            subtitle: "Develops upper body and core strength through controlled lowering.",
            duration: "8 mins",
            description: "Develops upper body and core strength through controlled lowering.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "py-4",
            title: "Crow Pose",
            subtitle: "An arm-balance posture that builds wrist, arm, and core strength.",
            duration: "9 mins",
            description: "An arm-balance posture that builds wrist, arm, and core strength.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "standing-yoga",
        name: "Standing Yoga",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "stdy-1",
            title: "Mountain Pose",
            subtitle:
              "The foundation of all standing poses, improving posture and grounding energy.",
            duration: "5 mins",
            description:
              "The foundation of all standing poses, improving posture and grounding energy.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "stdy-2",
            title: "Tree Pose",
            subtitle: "Improves balance and concentration while strengthening the legs.",
            duration: "6 mins",
            description: "Improves balance and concentration while strengthening the legs.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "stdy-3",
            title: "Triangle Pose",
            subtitle: "Stretches the sides of the body and opens the chest and hips.",
            duration: "7 mins",
            description: "Stretches the sides of the body and opens the chest and hips.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "stdy-4",
            title: "Chair Pose",
            subtitle: "Strengthens the thighs and ankles while toning the core.",
            duration: "5 mins",
            description: "Strengthens the thighs and ankles while toning the core.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
    ],
  },
  {
    id: "soft-fitness",
    name: "Soft Fitness",
    subCategories: [
      {
        id: "gentle-stretching",
        name: "Gentle Stretching",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "gs-1",
            title: "Neck Rolls",
            subtitle:
              "Releases tension in the neck and upper shoulders with slow circular movements.",
            duration: "4 mins",
            description:
              "Releases tension in the neck and upper shoulders with slow circular movements.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "gs-2",
            title: "Hip Flexor Stretch",
            subtitle: "Opens tight hip flexors caused by long periods of sitting.",
            duration: "6 mins",
            description: "Opens tight hip flexors caused by long periods of sitting.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "gs-3",
            title: "Chest Opener",
            subtitle: "Counteracts rounded shoulders and improves breathing capacity.",
            duration: "5 mins",
            description: "Counteracts rounded shoulders and improves breathing capacity.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "gs-4",
            title: "Hamstring Stretch",
            subtitle: "Lengthens the hamstrings and reduces lower back stiffness.",
            duration: "5 mins",
            description: "Lengthens the hamstrings and reduces lower back stiffness.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "low-impact-cardio",
        name: "Low Impact Cardio",
        status: "active",
        exerciseCount: 3,
        exercises: [
          {
            id: "lic-1",
            title: "Marching in Place",
            subtitle: "A gentle cardiovascular warm-up that elevates the heart rate safely.",
            duration: "8 mins",
            description: "A gentle cardiovascular warm-up that elevates the heart rate safely.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "lic-2",
            title: "Side Steps",
            subtitle: "Improves lateral movement, coordination, and cardiovascular health.",
            duration: "7 mins",
            description: "Improves lateral movement, coordination, and cardiovascular health.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "lic-3",
            title: "Seated Leg Lifts",
            subtitle: "Strengthens the core and hip flexors without stress on the joints.",
            duration: "6 mins",
            description: "Strengthens the core and hip flexors without stress on the joints.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "balance-training",
        name: "Balance Training",
        status: "active",
        exerciseCount: 3,
        exercises: [
          {
            id: "bt-1",
            title: "Single Leg Stand",
            subtitle: "Develops ankle stability and proprioception through single-leg balance.",
            duration: "5 mins",
            description: "Develops ankle stability and proprioception through single-leg balance.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "bt-2",
            title: "Heel-to-Toe Walk",
            subtitle: "Improves gait and balance through focused mindful walking.",
            duration: "6 mins",
            description: "Improves gait and balance through focused mindful walking.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "bt-3",
            title: "Bosu Ball Squats",
            subtitle: "Challenges the core and lower body stabilisers on an unstable surface.",
            duration: "8 mins",
            description: "Challenges the core and lower body stabilisers on an unstable surface.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
    ],
  },
  {
    id: "pilates",
    name: "Pilates",
    subCategories: [
      {
        id: "mat-pilates",
        name: "Mat Pilates",
        status: "active",
        exerciseCount: 4,
        exercises: [
          {
            id: "mp-1",
            title: "The Hundred",
            subtitle: "A classic Pilates warm-up that activates the core and promotes circulation.",
            duration: "5 mins",
            description:
              "A classic Pilates warm-up that activates the core and promotes circulation.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "mp-2",
            title: "Roll Up",
            subtitle:
              "Builds abdominal strength and spinal articulation through a slow controlled movement.",
            duration: "6 mins",
            description:
              "Builds abdominal strength and spinal articulation through a slow controlled movement.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "mp-3",
            title: "Single Leg Circle",
            subtitle: "Mobilises the hip joint and strengthens the core stabilisers.",
            duration: "5 mins",
            description: "Mobilises the hip joint and strengthens the core stabilisers.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "mp-4",
            title: "Swan Dive",
            subtitle: "Strengthens the back extensors and opens the front body.",
            duration: "7 mins",
            description: "Strengthens the back extensors and opens the front body.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "core-pilates",
        name: "Core Pilates",
        status: "active",
        exerciseCount: 3,
        exercises: [
          {
            id: "cp-1",
            title: "Plank Hold",
            subtitle: "Engages the entire core, shoulders, and glutes for total-body stability.",
            duration: "5 mins",
            description: "Engages the entire core, shoulders, and glutes for total-body stability.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "cp-2",
            title: "Dead Bug",
            subtitle: "Trains deep core stability while keeping the spine neutral.",
            duration: "6 mins",
            description: "Trains deep core stability while keeping the spine neutral.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "cp-3",
            title: "Criss-Cross",
            subtitle: "Targets the obliques through a rotational movement pattern.",
            duration: "7 mins",
            description: "Targets the obliques through a rotational movement pattern.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
      {
        id: "reformer-pilates",
        name: "Reformer Pilates",
        status: "active",
        exerciseCount: 3,
        exercises: [
          {
            id: "rp-1",
            title: "Footwork Series",
            subtitle:
              "Develops lower body alignment and strength using the reformer spring resistance.",
            duration: "10 mins",
            description:
              "Develops lower body alignment and strength using the reformer spring resistance.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "rp-2",
            title: "Long Stretch",
            subtitle:
              "Challenges the core and shoulder stability in a plank-like position on the reformer.",
            duration: "8 mins",
            description:
              "Challenges the core and shoulder stability in a plank-like position on the reformer.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
          {
            id: "rp-3",
            title: "Elephant",
            subtitle: "Stretches the spine and hamstrings while building core control.",
            duration: "7 mins",
            description: "Stretches the spine and hamstrings while building core control.",
            status: "active",
            videoUrl: "#",
            audioUrl: "#",
            createdAt: new Date().toISOString(),
          },
        ],
      },
    ],
  },
];

export const mindfulExerciseService: IMindfulExerciseService = {
  getCategories: async (): Promise<ExerciseCategory[]> => {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 500));
    return MOCK_CATEGORIES;
  },

  getSubCategoryById: async (id: string): Promise<ExerciseSubCategory | null> => {
    await new Promise((resolve) => setTimeout(resolve, 300));
    for (const cat of MOCK_CATEGORIES) {
      const sub = cat.subCategories.find((subCategory) => subCategory.id === id);
      if (sub) return sub;
    }
    return null;
  },

  addCategory: async (data: unknown) => {
    console.log("Adding Category:", data);
    return { id: Math.random().toString(36).substr(2, 9), ...(data as object) };
  },

  addExercise: async (subCategoryId: string, data: unknown) => {
    console.log(`Adding Exercise to ${subCategoryId}:`, data);
    return { id: Math.random().toString(36).substr(2, 9), ...(data as object) };
  },
};
